// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/BUGLAN/thoth/crawler/process"
	"github.com/BUGLAN/thoth/dao"
	"github.com/BUGLAN/thoth/internal/pkg/es"
	"github.com/BUGLAN/thoth/internal/pkg/mongo"
	"github.com/BUGLAN/thoth/internal/thoth/service"
	"github.com/globalsign/mgo"
	"github.com/olivere/elastic/v7"
)

// Injectors from wire.go:

func InitBookDao() dao.BookDao {
	database := InitMongo()
	bookDao := dao.NewBook(database)
	return bookDao
}

func InitArticleDao() dao.ArticleDao {
	client := InitEs()
	articleDao := dao.NewArticle(client)
	return articleDao
}

func InitArticleService() service.ArticleService {
	client := InitEs()
	articleDao := dao.NewArticle(client)
	articleService := service.NewArticleService(articleDao)
	return articleService
}

func InitKanShuProcess() *process.KanShu {
	bookDao := InitBookDao()
	articleDao := InitArticleDao()
	kanShu := process.NewKanShu(bookDao, articleDao)
	return kanShu
}

// wire.go:

func InitMongo() *mgo.Database {
	return mongo.Init(&mongo.Config{
		Username:   "root",
		Password:   "root",
		ServerList: "localhost:27017",
		Database:   "admin",
		Option:     "",
		PoolLimit:  20,
	})

}

func InitEs() *elastic.Client {
	return es.Init(&es.Config{ServerURLs: []string{"http://127.0.0.1:9200"}})
}
