// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/BUGLAN/thoth/dao"
	"github.com/BUGLAN/thoth/internal/pkg/es"
	"github.com/BUGLAN/thoth/internal/pkg/mongo"
	"github.com/BUGLAN/thoth/internal/thoth"
	"github.com/globalsign/mgo"
	"github.com/olivere/elastic/v7"
)

// Injectors from wire.go:

func InitBookDao() (dao.BookDao, error) {
	database, err := InitMongo()
	if err != nil {
		return nil, err
	}
	bookDao := dao.NewBook(database)
	return bookDao, nil
}

func InitThothController() (*thoth.Controller, error) {
	bookDao, err := InitBookDao()
	if err != nil {
		return nil, err
	}
	controller := thoth.NewThothController(bookDao)
	return controller, nil
}

// wire.go:

func InitMongo() (*mgo.Database, error) {
	return mongo.Init(&mongo.Config{
		Username:   "root",
		Password:   "root",
		ServerList: "localhost:27017",
		Database:   "admin",
		Option:     "",
		PoolLimit:  20,
	})

}

func InitEs() (*elastic.Client, error) {
	return es.Init(&es.Config{ServerURLs: []string{"http://127.0.0.1:9200"}})
}
