// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/BUGLAN/thoth/dao"
	"github.com/BUGLAN/thoth/internal/pkg/mongo"
	"github.com/BUGLAN/thoth/internal/thoth"
	"github.com/globalsign/mgo"
)

// Injectors from wire.go:

func InitBookDao() (dao.BookDao, error) {
	database, err := InitMongoConfig()
	if err != nil {
		return nil, err
	}
	bookDao := dao.NewBook(database)
	return bookDao, nil
}

func InitThothController() (*thoth.Controller, error) {
	bookDao, err := InitBookDao()
	if err != nil {
		return nil, err
	}
	controller := thoth.NewThothController(bookDao)
	return controller, nil
}

// wire.go:

func InitMongoConfig() (*mgo.Database, error) {
	return mongo.Init(&mongo.Config{
		Username:   "root",
		Password:   "root",
		ServerList: "localhost:27017",
		Database:   "admin",
		Option:     "",
		PoolLimit:  20,
	})

}
